apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitor-deploy
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "labels" . | nindent 6 }}
  template:
    metadata:
      name: flask-monitor-pod
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      containers:
        - name: flask-monitor-container
          image: {{ .Values.image }}:{{ .Values.tag | default "latest" }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: my_access_key_id
              ValueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: ACCESS_KEY_EXAMPLE
            - name: my_secret_access_key
              ValueFrom:
                secretKeyRef:
                  name: flask-monitor-secret
                  key: SECRET_KEY_EXAMPLE

