apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-aws-monitor-ingress
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: flask-monitor.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-monitor-svc
                port:
                  number: {{ .Values.service.port }}
